name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*.*.*'    # Chỉ trigger khi push tag dạng vX.Y.Z

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile convert.py

    - name: Upload artifact for release
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/convert.exe

  release:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: windows-exe
            path: ./artifact

        - name: Set up GitHub CLI
          uses: cli/cli-action@v2

        - name: Create Release and Upload EXE
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release create ${{ github.ref_name }} ./artifact/convert.exe --title "Release ${{ github.ref_name }}" --notes "Windows executable for version ${{ github.ref_name }}"

