name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*.*.*'    # Trigger khi push tag dạng vX.Y.Z

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyinstaller pillow

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile convert.py

      - name: Copy EXE and ICC files to output folder
        run: |
          mkdir release_files
          copy dist\convert.exe release_files\
          copy CoatedFOGRA27.icc release_files\
          copy sRGB_v4_ICC_preference.icc release_files\

      - name: Zip release content
        run: Compress-Archive -Path release_files\* -DestinationPath release.zip

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download zipped artifact
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: ./

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ✅ Windows release for version `${{ github.ref_name }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

